# @package _global_

root:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  max_steps: 20000
  accelerator: gpu
  devices: ${devices}
  precision: 32-true
  log_every_n_steps: 50
  val_check_interval: 100
  strategy: ddp
  num_sanity_val_steps: 0
