[project]
name = "grid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "datasets>=5.0.0",
    "transformers>=5.12.1",
    "hydra-colorlog>=1.2.0",
    "lightning==2.6.5",
    "matplotlib>=3.11.0",
    "modelscope>=1.38.0",
    "rootutils>=1.0.7",
    "sentencepiece==0.2.1",
    "tensorflow-cpu==2.21.0",
    "tfrecord==1.14.6",
    "torch==2.9.1",
    "torchaudio==2.9.1",
    "torchmetrics==1.0.3",
    "torchvision==0.24.1",
    "wandb>=0.28.0",
    "hydra-core>=1.3.3",
    # 仅 Linux 安装
    "torchrec==1.4.0; sys_platform == 'linux'",
    "pytz>=2026.2",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[dependency-groups]
dev = [
    "notebook>=7.6.0",
    "ruff>=0.15.20",
    "icecream>=2.2.0",
]
