[project]
name = "grid"
version = "0.1.0"
description = "GRID Windows 开发最小依赖环境"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "fsspec>=2024.9.0",
    "hydra-colorlog==1.2.0",
    "hydra-core>=1.3,<1.4",
    "lightning==2.5.0",
    "numpy>=1.26,<3",
    "omegaconf>=2.3,<3",
    "psutil>=5.9,<8",
    "pyarrow>=17,<22",
    "python-dotenv>=1.0,<2",
    "pytz>=2024.1",
    "rich>=13,<15",
    "rootutils==1.0.7",
    "sentencepiece==0.2.0",
    "tokenizers>=0.20,<0.22",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "torchmetrics>=1.6,<2",
    "torchvision==0.21.0",
    "transformers>=4.48,<5",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[dependency-groups]
dev = [
    "notebook>=7.5.7",
]
