# @package _global_

root:
  _target_: src.quantization.rkmeans.residual_kmeans.ResidualKMeans
  n_layers: ${num_hierarchies}
  n_clusters: ${codebook_size}
  n_features: ${embedding_dim}
  init_buffer_size: 3072
  optimizer: null
  scheduler: null
