# @package _global_

root:
  _target_: src.quantization.rkmeans.residual_kmeans.ResidualKMeans
  n_layers: ${num_hierarchies}
  n_clusters: ${codebook_size}
  n_features: ${embedding_dim}
  training_model_config: ${model.training_model_config}
  sub_layer:
    _target_: src.quantization.rkmeans.kmeans_layer.KMeansLayer
    _partial_: true
    n_clusters: ${codebook_size}
    n_features: ${embedding_dim}
    init_buffer_size: 3072

training_model_config:
  _target_: src.common.configs.model.TrainingModelConfig
  loss_function:
    _target_: src.common.components.loss_functions.WeightedSquaredError
  optimizer:
    _target_: torch.optim.SGD
    _partial_: true
    lr: 0.5
  scheduler:
    _target_: src.common.components.scheduler.WarmupCosineSchedulerNonzeroMin
    _partial_: true
    warmup_steps: 100
    min_ratio: 0.3
    scheduler_steps: ${trainer.root.max_steps}
