# @package _global_

root:
  _target_: src.quantization.residual_quantization_vae.ResidualQuantizationVAE
  n_layers: ${num_hierarchies}
  n_clusters: ${codebook_width}
  n_features: ${model.encoder.output_dim}
  loss_function: ${model.loss_function}
  init_buffer_size: 3072
  initialize_on_cpu: false
  normalize_residuals: false
  track_residuals: true
  kmeans_max_iter: 1000
  normalization_layer: ${model.normalization_layer}
  encoder: ${model.encoder}
  decoder: ${model.decoder}
  reconstruction_loss_function: ${model.reconstruction_loss_function}
  reconstruction_loss_weight: 1.0
  training_loop_function: ${model.training_loop_function}
  optimizer: ${model.optimizer}
  scheduler: null
loss_function:
  _target_: src.common.components.loss_functions.BetaQuantizationLoss
  beta: 0.25
  reduction: mean
normalization_layer:
  _target_: torch.nn.Sequential
  _args_:
  - _target_: torch.nn.BatchNorm1d
    num_features: ${embedding_dim}
  - _target_: src.common.modules.normalize_layer.NormalizeLayer
encoder:
  _target_: src.common.modules.mlp.MLP
  input_dim: ${embedding_dim}
  hidden_dim_list:
  - 768
  - 256
  - 128
  output_dim: 64
  activation:
    _target_: torch.nn.ReLU
    _partial_: true
decoder:
  _target_: src.common.modules.mlp.MLP
  input_dim: ${model.encoder.output_dim}
  hidden_dim_list:
  - 128
  - 256
  - 768
  output_dim: ${embedding_dim}
  activation:
    _target_: torch.nn.ReLU
    _partial_: true
reconstruction_loss_function:
  _target_: torch.nn.MSELoss
  reduction: mean
training_loop_function:
  _target_: src.quantization.training_loop_functions.scale_loss_by_world_size_for_initialization_training_loop
  _partial_: true
optimizer:
  _target_: torch.optim.Adagrad
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
