# @package _global_

root:
  _target_: src.quantization.rqvae.residual_quantization_vae.ResidualQuantizationVAE
  n_layers: ${num_hierarchies}
  n_clusters: ${codebook_size}
  n_features: ${model.encoder.output_dim}
  training_model_config: ${model.training_model_config}
  init_buffer_size: 3072
  normalize_residuals: false
  kmeans_max_iter: 1000
  normalization_layer: ${model.normalization_layer}
  encoder: ${model.encoder}
  decoder: ${model.decoder}
  reconstruction_loss_weight: 1.0

training_model_config:
  _target_: src.common.configs.model.TrainingModelConfig
  loss_function:
    _target_: src.common.components.loss_functions.BetaQuantizationLoss
    beta: 0.25
    reduction: mean
  reconstruction_loss_function:
    _target_: torch.nn.MSELoss
    reduction: mean
  optimizer:
    _target_: torch.optim.Adagrad
    _partial_: true
    lr: 0.001
    weight_decay: 0.0
  scheduler: null

metrics:
  _target_: src.common.metrics.MetricEngine
  stages:
    train:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: loss
      quantization_loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: quantization_loss
      reconstruction_loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: reconstruction_loss
      first_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: first_residuals_norm_ratio
      last_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: last_residuals_norm_ratio
      first_centroids_norm:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: first_centroids_norm
      last_centroids_norm:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: last_centroids_norm
      frac_unique_ids:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: frac_unique_ids
      mse:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: mse
      layer_coverages:
        repeat:
          count: ${num_hierarchies}
          index_name: layer_idx
          name_template: layer_{layer_idx}/frac_layer_coverages
          metric:
            _target_: torchmetrics.MeanMetric
          spec:
            key: layer_coverages
            index: "{layer_idx}"
      layer_id_entropy:
        repeat:
          count: ${num_hierarchies}
          index_name: layer_idx
          name_template: layer_{layer_idx}/id_entropy
          metric:
            _target_: torchmetrics.MeanMetric
          spec:
            key: layer_id_entropies
            index: "{layer_idx}"
    val:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: loss
      first_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: first_residuals_norm_ratio
      last_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: last_residuals_norm_ratio
      frac_unique_ids:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: frac_unique_ids
      mse:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: mse
    test:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: loss
      first_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: first_residuals_norm_ratio
      last_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: last_residuals_norm_ratio
      frac_unique_ids:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: frac_unique_ids
      mse:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: mse

normalization_layer:
  _target_: torch.nn.Sequential
  _args_:
  - _target_: torch.nn.BatchNorm1d
    num_features: ${embedding_dim}
  - _target_: src.quantization.rqvae.normalize_layer.NormalizeLayer
encoder:
  _target_: src.quantization.rqvae.mlp.MLP
  input_dim: ${embedding_dim}
  hidden_dim_list:
  - 768
  - 256
  - 128
  output_dim: 64
  activation:
    _target_: torch.nn.ReLU
    _partial_: true
decoder:
  _target_: src.quantization.rqvae.mlp.MLP
  input_dim: ${model.encoder.output_dim}
  hidden_dim_list:
  - 128
  - 256
  - 768
  output_dim: ${embedding_dim}
  activation:
    _target_: torch.nn.ReLU
    _partial_: true
