# @package _global_

root:
  _target_: src.quantization.rvq.residual_vector_quantization.ResidualVectorQuantization
  n_layers: ${num_hierarchies}
  n_clusters: ${codebook_width}
  n_features: ${embedding_dim}
  loss_function: ${model.loss_function}
  init_buffer_size: 3072
  normalize_residuals: true
  optimizer: ${model.optimizer}
  scheduler: null
loss_function:
  _target_: src.common.components.loss_functions.BetaQuantizationLoss
  beta: 0.25
optimizer:
  _target_: torch.optim.Adagrad
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
