# @package _global_

root:
  _target_: src.quantization.residual_quantization.ResidualQuantization
  track_residuals: true
  verbose: true
  train_layer_wise: true
  normalize_residuals: true
  input_dim: ${embedding_dim}
  n_layers: ${num_hierarchies}
  init_buffer_size: 3072
  quantization_layer: ${model.quantization_layer}
  optimizer: ${optim.optimizer}
  scheduler: null
  quantization_layer_list: null
  training_loop_function: ${model.training_loop_function}
quantization_layer:
  _target_: src.quantization.vector_quantization.VectorQuantization
  n_clusters: ${codebook_width}
  n_features: ${model.root.input_dim}
  distance_function:
    _target_: src.common.components.distance_functions.SquaredEuclideanDistance
  quantization_strategy:
    _target_: src.common.components.quantization_strategies.STEQuantization
    distance_function: ${model.quantization_layer.distance_function}
    compute_reconstruction_loss_embeddings: false
  initializer:
    _target_: src.common.components.clustering_initializers.KMeansPlusPlusInitInitializer
    n_clusters: ${codebook_width}
    initialize_on_cpu: false
    distance_function: ${model.quantization_layer.distance_function}
  init_buffer_size: ${model.root.init_buffer_size}
  loss_function:
    _target_: src.common.components.loss_functions.BetaQuantizationLoss
    beta: 0.25
  optimizer: null
training_loop_function:
  _target_: src.quantization.training_loop_functions.scale_loss_by_world_size_for_initialization_training_loop
  _partial_: true
