# @package _global_

root:
  _target_: src.quantization.rvq.residual_vector_quantization.ResidualVectorQuantization
  n_layers: ${num_hierarchies}
  n_clusters: ${codebook_size}
  n_features: ${embedding_dim}
  training_model_config: ${model.training_model_config}
  normalize_residuals: true
  sub_layer:
    _target_: src.quantization.rvq.vector_quantization_layer.VectorQuantizationLayer
    _partial_: true
    n_clusters: ${codebook_size}
    n_features: ${embedding_dim}
    init_buffer_size: 3072

training_model_config:
  _target_: src.common.configs.model.TrainingModelConfig
  loss_function:
    _target_: src.common.loss.beta_quantization_loss.BetaQuantizationLoss
    beta: 0.25
    reduction: mean
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.001
    weight_decay: 0.0
  scheduler: null

metrics:
  _target_: src.common.metrics.MetricEngine
  stages:
    train:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: loss
      quantization_loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: quantization_loss
      first_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: first_residuals_norm_ratio
      last_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: last_residuals_norm_ratio
      first_centroids_norm:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: first_centroids_norm
      last_centroids_norm:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: last_centroids_norm
      frac_unique_ids:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: frac_unique_ids
      mse:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: mse
      layer_coverages:
        repeat:
          count: ${num_hierarchies}
          index_name: layer_idx
          name_template: layer_{layer_idx}/frac_layer_coverages
          metric:
            _target_: torchmetrics.MeanMetric
          spec:
            key: layer_coverages
            index: "{layer_idx}"
      layer_id_entropy:
        repeat:
          count: ${num_hierarchies}
          index_name: layer_idx
          name_template: layer_{layer_idx}/id_entropy
          metric:
            _target_: torchmetrics.MeanMetric
          spec:
            key: layer_id_entropies
            index: "{layer_idx}"
    val:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: loss
      first_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: first_residuals_norm_ratio
      last_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: last_residuals_norm_ratio
      frac_unique_ids:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: frac_unique_ids
      mse:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: mse
    test:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: loss
      first_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: first_residuals_norm_ratio
      last_residuals_norm_ratio:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: last_residuals_norm_ratio
      frac_unique_ids:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: frac_unique_ids
      mse:
        metric:
          _target_: torchmetrics.MeanMetric
        spec: mse
