# @package _global_

semantic_embedding_model:
  _target_: src.embedding.hf_language_model.HFLanguageModel
  huggingface_model:
    _target_: transformers.T5EncoderModel.from_pretrained
    pretrained_model_name_or_path: ${embedding_model}
  aggregator:
    _target_: src.embedding.embedding_aggregator.EmbeddingAggregator

root:
  _target_: src.embedding.semantic_embedder.SemanticEmbedder
  semantic_embedding_model_input_map:
    input_ids: text_tokens
    attention_mask: text_mask
  semantic_embedding_model: ${model.semantic_embedding_model}
