# @package _global_

root:
  _target_: src.recommendation.tiger.Tiger
  encoder: ${model.encoder}
  training_model_config: ${model.training_model_config}
  decoder: ${model.decoder}
  semantic_ids:
    _target_: src.data.utils.load_semantic_id_tensor
    file_path: ${semantic_id_path}
  num_hierarchies: ${num_hierarchies}
  codebook_size: ${codebook_size}
  embedding_dim: 256
  should_check_prefix: true

encoder:
  _target_: transformers.T5EncoderModel
  config:
    _target_: transformers.T5Config
    vocab_size: ${model.root.codebook_size}
    d_model: ${model.root.embedding_dim}
    num_heads: 4
    dropout_rate: 0.1
    d_ff: 1024
    d_kv: 64
    num_layers: 4

decoder:
  _target_: transformers.models.t5.modeling_t5.T5Stack
  config:
    _target_: transformers.models.t5.configuration_t5.T5Config
    vocab_size: ${model.encoder.config.vocab_size}
    d_model: ${model.root.embedding_dim}
    num_heads: ${model.encoder.config.num_heads}
    dropout_rate: ${model.encoder.config.dropout_rate}
    d_ff: ${model.encoder.config.d_ff}
    d_kv: ${model.encoder.config.d_kv}
    num_layers: ${model.encoder.config.num_layers}
    is_decoder: true
    is_encoder_decoder: false

training_model_config:
  _target_: src.common.configs.model.TrainingModelConfig
  loss_function:
    _target_: torch.nn.CrossEntropyLoss
    ignore_index: -1
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0003
    weight_decay: 0.001
  scheduler:
    _target_: src.common.components.scheduler.WarmupCosineSchedulerNonzeroMin
    _partial_: true
    warmup_steps: 1000
    min_ratio: 0.05
    scheduler_steps: ${trainer.root.max_steps}

metrics:
  _target_: src.common.metrics.MetricEngine
  stages:
    train:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: loss
    val:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: loss
      ndcg@5:
        metric:
          _target_: src.recommendation.tiger.metrics.NDCG
          top_k: 5
          sync_on_compute: false
          compute_with_cache: false
        spec:
          adapter:
            _target_: src.recommendation.tiger.metrics.sid_retrieval_inputs
            _partial_: true
      ndcg@10:
        metric:
          _target_: src.recommendation.tiger.metrics.NDCG
          top_k: 10
          sync_on_compute: false
          compute_with_cache: false
        spec:
          adapter:
            _target_: src.recommendation.tiger.metrics.sid_retrieval_inputs
            _partial_: true
      recall@5:
        metric:
          _target_: src.recommendation.tiger.metrics.Recall
          top_k: 5
          sync_on_compute: false
          compute_with_cache: false
        spec:
          adapter:
            _target_: src.recommendation.tiger.metrics.sid_retrieval_inputs
            _partial_: true
      recall@10:
        metric:
          _target_: src.recommendation.tiger.metrics.Recall
          top_k: 10
          sync_on_compute: false
          compute_with_cache: false
        spec:
          adapter:
            _target_: src.recommendation.tiger.metrics.sid_retrieval_inputs
            _partial_: true
    test:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        spec:
          key: loss
      ndcg@5:
        metric:
          _target_: src.recommendation.tiger.metrics.NDCG
          top_k: 5
          sync_on_compute: false
          compute_with_cache: false
        spec:
          adapter:
            _target_: src.recommendation.tiger.metrics.sid_retrieval_inputs
            _partial_: true
      ndcg@10:
        metric:
          _target_: src.recommendation.tiger.metrics.NDCG
          top_k: 10
          sync_on_compute: false
          compute_with_cache: false
        spec:
          adapter:
            _target_: src.recommendation.tiger.metrics.sid_retrieval_inputs
            _partial_: true
      recall@5:
        metric:
          _target_: src.recommendation.tiger.metrics.Recall
          top_k: 5
          sync_on_compute: false
          compute_with_cache: false
        spec:
          adapter:
            _target_: src.recommendation.tiger.metrics.sid_retrieval_inputs
            _partial_: true
      recall@10:
        metric:
          _target_: src.recommendation.tiger.metrics.Recall
          top_k: 10
          sync_on_compute: false
          compute_with_cache: false
        spec:
          adapter:
            _target_: src.recommendation.tiger.metrics.sid_retrieval_inputs
            _partial_: true
