# @package _global_

root:
  _target_: src.recommendation.tiger.Tiger
  encoder: ${model.encoder}
  training_model_config: ${model.training_model_config}
  decoder: ${model.decoder}
  semantic_ids:
    _target_: src.inference.utils.load_semantic_id_tensor
    file_path: ${semantic_id_path}
  num_hierarchies: ${num_hierarchies}
  codebook_size: ${codebook_size}
  embedding_dim: ${embedding_dim}
  should_check_prefix: true

encoder:
  _target_: transformers.T5EncoderModel
  config:
    _target_: transformers.T5Config
    vocab_size: 256
    d_model: 128
    num_heads: 6
    dropout_rate: 0.1
    d_ff: 1024
    d_kv: 64
    num_layers: 4

decoder:
  _target_: transformers.models.t5.modeling_t5.T5Stack
  config:
    _target_: transformers.models.t5.configuration_t5.T5Config
    vocab_size: ${model.encoder.config.vocab_size}
    d_model: ${model.encoder.config.d_model}
    num_heads: ${model.encoder.config.num_heads}
    dropout_rate: 0.1
    d_ff: ${model.encoder.config.d_ff}
    d_kv: ${model.encoder.config.d_kv}
    num_layers: 4
    is_decoder: true
    is_encoder_decoder: false

training_model_config:
  _target_: src.common.configs.model.TrainingModelConfig
  loss_function:
    _target_: torch.nn.CrossEntropyLoss
    ignore_index: -1
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0003
    weight_decay: 0.001
  scheduler:
    _target_: src.common.components.scheduler.WarmupCosineSchedulerNonzeroMin
    _partial_: true
    warmup_steps: 1000
    min_ratio: 0.05
    scheduler_steps: ${trainer.root.max_steps}

metrics:
  _target_: src.common.metrics.MetricEngine
  stages:
    train:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        input: loss
    val:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        input: loss
      retrieval:
        name: ""
        metric:
          _target_: src.common.metrics.SIDRetrievalMetricGroup
          top_k_list:
          - 5
          - 10
          metrics:
            ndcg:
              _target_: src.common.components.eval_metrics.NDCG
              _partial_: true
            recall:
              _target_: src.common.components.eval_metrics.Recall
              _partial_: true
    test:
      loss:
        metric:
          _target_: torchmetrics.MeanMetric
        input: loss
      retrieval:
        name: ""
        metric:
          _target_: src.common.metrics.SIDRetrievalMetricGroup
          top_k_list:
          - 5
          - 10
          metrics:
            ndcg:
              _target_: src.common.components.eval_metrics.NDCG
              _partial_: true
            recall:
              _target_: src.common.components.eval_metrics.Recall
              _partial_: true
