# -----------------------------
# Root and input paths
# -----------------------------
root_dir: .
data_dir: ${data_dir}

# -----------------------------
# Runtime output paths
# -----------------------------
log_dir: ${paths.root_dir}/logs
output_dir: ${hydra:runtime.output_dir}

work_dir: ${hydra:runtime.cwd}

# Keep profiler output separate because gcs paths are not supported directly.
profile_dir: ${hydra:run.dir}/profile_output

metadata_dir: ${paths.output_dir}/metadata

# -----------------------------
# Asset paths
# -----------------------------
pretrained_models_dir: ${paths.root_dir}/pretrained_models
