import json
import os
from pathlib import Path
from typing import BinaryIO

from fsspec.core import url_to_fs

from src.utils.decorators import retry
from src.utils.pylogger import RankedLogger

logger = RankedLogger(__name__, rank_zero_only=True)


@retry()
def get_file_size(file_path: str) -> int:
    fs, _ = url_to_fs(file_path)
    return fs.size(file_path)


@retry()
def open_local_or_remote(file_path: str, mode: str = "r") -> BinaryIO:
    fs, _ = url_to_fs(file_path)
    return fs.open(file_path, mode)


def load_json(file_path: str) -> dict:
    with open_local_or_remote(file_path, "r") as f:
        feature_map = json.load(f)
    return feature_map


def get_last_modified_file(folder_path: str, suffix="*", should_update_prefix=True) -> str:
    """
    Can get the last modified file in a folder from a local or remote filesystem.
    """
    fs, _ = url_to_fs(folder_path)
    file_list = list_files(folder_path, suffix, should_update_prefix)
    if not file_list:
        return ""

    latest_file = ""
    latest_mtime = 0
    for file in file_list:
        info = fs.info(file)
        mtime = info.get("mtime", 0)
        if latest_mtime == 0 or mtime > latest_mtime:
            latest_mtime = mtime
            latest_file = file
    return latest_file


def has_no_extension(filepath: str) -> bool:
    # Extract just the filename from the path, handles both local and cloud paths
    filename = os.path.basename(filepath)
    # Split the filename and check if extension is empty
    _, extension = os.path.splitext(filename)
    return extension == ""


def list_subfolders(
    directory_path,
    should_update_prefix: bool = True,
):
    """
    List all folders inside a directory using fsspec.

    Args:
        directory_path (str): Path to the directory to search
                             (can be local or remote like 's3://', 'gs://', etc.)
        should_update_prefix (bool): If True, adds the prefix based on the filesystem,
                                     otherwise returns the path generated by glob
    Returns:
        list: List of folder paths
    """
    # Get the appropriate filesystem
    fs, _ = url_to_fs(directory_path)

    # List all items in the directory
    all_items = fs.ls(directory_path)

    # Filter to only include directories that are not the original one.
    folders = [
        f"{fs.protocol[0]}://{item}" if should_update_prefix else item
        for item in all_items
        if fs.isdir(item) and item != directory_path
    ]

    return folders


@retry()
def list_files(
    folder_path: str,
    suffix: str = "*",
    # if should_update_prefix is True, adds the prefix based on the filesystem,
    # otherwise returns the path generated by glob
    should_update_prefix: bool = True,
) -> list[str]:

    # We remove trailing slashes to avoid double slashes in the path
    folder_path = folder_path.removesuffix("/")

    fs, _ = url_to_fs(folder_path)
    return (
        # add the prefix for gcs.
        [f"{fs.protocol[0]}://{x}" for x in fs.glob(f"{folder_path}/{suffix}")]
        if should_update_prefix
        else fs.glob(f"{folder_path}/{suffix}")
    )


def sync_file(path: str):
    path = Path(path)
    if hasattr(os, "sync"):
        os.sync()
    if path.is_file():
        with open(path, "rb") as f:
            os.fsync(f.fileno())
    elif path.is_dir() and hasattr(os, "O_DIRECTORY"):
        dir_fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
