# @package _global_

pickle_writer:
  _target_: src.common.components.prediction_writers.LocalPickleWriter
  output_dir: ${paths.output_dir}/pickle
  flush_frequency: 100000
  write_interval: batch
  should_merge_files_on_main: true
  prediction_key_name: item_id
  prediction_name: cluster_ids
  post_processing_functions:
  - _target_: src.utils.tensor_utils.deduplicate_rows_in_tensor
    _partial_: true
