# @package _global_

defaults:
  - _self_
  - paths: default
  - logger: default
  - trainer: default
  - hydra: default
  - data_loading: null
  - extras: default
  - experiment: null

task_name: "inference"
id: ${now_tz:%Y-%m-%d}/${now_tz:%H-%M-%S}
tags: ["inference"]

# passing checkpoint path is necessary for inference
ckpt_path: ???
